### ISSUE TITLE
Test code chunkify edge case

### ISSUE THREAD

**Issue by thomas-quadratic** [hyperledger/besu-verkle-trie#14]
### Description
Currently, chunkifyCode in TrieKeyAdaptor has been implemented and tested on two contract's bytecode.
However, we are uncertain of the validity of the current implementation in the case of PUSH32.
The ultimate edge-case would be to have a PUSH32 opcode at a position a multiple of 31. This would mean that the next code chunk is made of only push data, and that data even spills one byte into the next-next chunk.

Expected
A testcase for the described edge-case. It should be added to the JSON test file.
If test fails, correct the current implementation so that it passes.

**Comment by gfukushima** [comment]
I'll see if can get to it this week yet.

**Comment by thomas-quadratic** [comment]
There seems to be this edge case in the genesis bytecode.
We have a code chunk with nPushData of 0x20 = 32, which is impossible
On geth, that chunk has nPushData  of 0x1f = 31, much better.
The other values are fine.

Seems like there is a bug afterall

**Comment by matkt** [comment]
This impacts the stateroot we get for the testnet . I think this bug is a blocking bug if we want to join the testnet
