### ISSUE TITLE
Fix commitment caching

### ISSUE THREAD

**Issue by thomas-quadratic** [hyperledger/besu-verkle-trie#16]
### Description
Computation of commitments should be done only if not already computed and up-to-date.
Currently, HashVisitor returns the cached value if the node is not dirty (has not been modified since last write in database) and if the commitment is non-empty. 
Note that it cannot detect if the commitment should be modified, or if commitment is up-to-date but other attributes are not.
Moreover, currently calling two getRootHash() in a row recomputes the hash, which it should not.

We therefore want to separate the logic of being up-to-date in the database and for the commitment.
Therefore, whenever the commitment is out-of-sync, it should be set to empty.

### Expected
1. Write a test that shows that commitments are not recomputed between two consecutive calls to getRootHash(). You could for example call getRootHash a first time, then hack the commitment value to a wrong value, make a second call and check that the second call returns the wrong value.
2. Modify PutVisitor to set commitments as empty whenever a leaf is modified.
3. Modify RemoveVisitor to set commitments as empty whenever a leaf is removed.

**Comment by neotheprogramist** [comment]
not needed given https://github.com/hyperledger/besu-verkle-trie/pull/20 fixes that for now
