### ISSUE TITLE
State Root with serialisation and not toScalars

### ISSUE THREAD

**Issue by thomas-quadratic** [hyperledger/besu-verkle-trie#27]
Currently, root hash is computed using the commit function, which returns the mapToScalars of the commitment.
However, it should be the serialized compressed representation of that commitment instead.

It is therefore expected that getRootHash() returns the value of commit_root instead of commit.
One should make the proper modifications to the code and to the test cases.

**Comment by neotheprogramist** [comment]
I'm working on that

**Comment by matkt** [comment]
done
