### ISSUE TITLE
Make verkle trie work with updateCommitmentSparse on stemNode

### ISSUE THREAD

**Issue by dragan2234** [hyperledger/besu-verkle-trie#41]
For the sparse update of the commitment, we'll need some workaround our java trie implemtation. Specifically:
https://github.com/hyperledger/besu-verkle-trie/blob/main/src/main/java/org/hyperledger/besu/ethereum/trie/verkle/visitor/HashVisitor.java#L79

This method currently just does this:
```
    hashes[2] = hasher.groupToField(hasher.commit(leftValues));
    hashes[3] = hasher.groupToField(hasher.commit(rightValues));
    final Bytes32 hash = hasher.groupToField(hasher.commit(hashes));
```

For LeftValues it should be:
```
hashes[2] = hasher.updateCommitmentSparse(oldC1, oldValuesArray, newValuesArray, indexes)
```
For right values:
```
hashes[3] = hasher.updateCommitmentSparse(oldC2, oldValuesArray, newValuesArray, indexes)
```
And for hash:
```
final Bytes32 hash = hasher.groupToField(hasher.updateCommitmentSparse(OldCommitment, oldValuesArray, newValuesArray, indexes));
```

Following the signature:
https://github.com/hyperledger/besu-native/blob/main/ipa-multipoint/src/main/java/org/hyperledger/besu/nativelib/ipamultipoint/LibIpaMultipoint.java#L75

**Potential issue is that maybe oldValues are not available in the context of hashVisitor, but i need to double-check that.**

**Comment by thomas-quadratic** [comment]
I am working on that
