### ISSUE TITLE
Batching TrieKeys Generation

### ISSUE THREAD

**Issue by thomas-quadratic** [hyperledger/besu-verkle-trie#45]
### Description
Currently, each trie key is generated with a call to the nativelib. However, moving to hash instead of compressed leads to a big optimisation opportunity: using hashMany is far more efficient.
This PR aims at batching all trie keys generation for a block into a single call to the native lib.

This depends on [PR 158](https://github.com/hyperledger/besu-native/pull/158)

**Comment by thomas-quadratic** [comment]
This requires modifications in Besu

**Comment by matkt** [comment]
will start to work on it
