### ISSUE TITLE
Idea: batch trie key generation inside a background thread

### ISSUE THREAD

**Issue by thomas-quadratic** [hyperledger/besu-verkle-trie#46]
### Description
Currently, trie keys generation will gather all transactions data and generate a single large batch of trie keys at once.
However, there are already mechanisms implemented in Besu to preload those trie keys in a background thread during block processing.
We should investigate using that mechanism.

**Comment by matkt** [comment]
maybe not really important. for the moment seems to be good with the current implementation but we will have to test with bigger blocks
