### ISSUE TITLE
Implement a batched hash visitor

### ISSUE THREAD

**Issue by thomas-quadratic** [hyperledger/besu-verkle-trie#48]
### Description
Currently, hashing is done node by node.
In geth, they use hashMany native function to make use of Montgoméry's optimisation to batch hashing level by level.
We should implement the same strategy in a new HashVisitor.
This new visitor might require a new Interface as well, returning List of Updated Nodes instead of the updated node.

**Comment by matkt** [comment]
will start to work on it
